### ISSUE TITLE
Enable source-build repo level prebuilts detection

### ISSUE THREAD

**Issue by tkapin** [dotnet/arcade-services#2360]
# Motivation

Currently, we detect new prebuilt introduction when source-building the whole product. This not only requires a lot of effort from the A&D team, but also takes significant time to remediate as the prebuilt detection is done late in the process. This late detection can seriously impact the product release as has been proven several times in the past.

Our goal is to introduce prebuilt detection on an individual product repo level so that developers could detect prebuilts during their PR validation and resolve the problem by generating the SBRPs themselves with minimum assistance from the A&D team.

# Business Objectives

- [ ] All repositories participating in the product construction have an explicit list of prebuilts specified
- [ ] Product developers have sufficient tooling and instructions to generate SBRPs without much support required from the A&D and Product Construction teams

# Milestones

- [x] Roslyn based SBRP generator PoC
- [x] Replace the current GenAPI tooling to use the new Roslyn features to generate SBRP sources
- [x] Enable repo-level prebuilts detection in all product repos
- [x] Improve customer experience when generating the SBRPs

**Comment by andriipatsula** [comment]
closing this one as done.
