### ISSUE TITLE
Investigate use of mirror service or other method to better surface inter-branch issues

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade-services#2655]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We've missed commits in servicing releases a few times now. The tough part is that during mirroring to internal/* branches, there are frequent, real conflicts that occur around when we merge into the open after a security release. It is important to note that these issues almost always require human intervention to determine what the right course of action is.

Right now you can watch the mirror pipelines and note which errors show up, manually check that the internal/* branches are up to date, etc. to ensure that things are working properly, but this info is not surfaced on BARViz, where CQBs are going to determine whether something is coherent and ready to ship. These issues are almost always discovered late.

I think the goals of this are:
- [ ] We need to ensure that the fact that internal/* is out of date w.r.t. the non internal/* branch is surfaced very clearly. It's almost always (but there are probably exceptions) an error.
- [ ] We need to ensure that the mirroring never misses a commit in the first place, due to dropped payloads or whatnot. This also ocassionally happens, but rarely.

The tough part is that our dependency flow and mirroring systems are disconnected today. Dependency flow doesn't understand the branch relationships (release/5.0 -> internal/release/5.0), and the mirroring definitions don't understand dependency flow. I think to surface this info in a reasonable well designed way we need to have that info be queryable by BARViz.

This leads back to an idea we had a long time ago, which was a real, configurable mirroring service that constantly ensured branches were up to date (direct mirrors or merge mirrors). Because this would have to understand the relationships, BARViz could be made to query it and surface that info.

Note that a shift to using GitHub repos alone would not remove the necessity of such info or such a service. The inter-branch merging from release/5.0->internal/release/5.0 will always remain, regardless of where the remote lives for each individual branch.

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

# Milestones 
- [x] https://github.com/dotnet/arcade/issues/9896

**Comment by premun** [comment]
I think this is done now with the new mirroring infrastructure
