### ISSUE TITLE
Implement support for codeflow subscriptions

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#2995]
# Context

As part of https://github.com/dotnet/arcade-services/issues/2994, a new service `.NET Product Construction Service` will be created. It will be processing the new codeflow-enabled subscriptions.
The details are described [here (`Full Code Flow.md`)](https://github.com/dotnet/arcade/blob/main/Documentation/UnifiedBuild/Full-Code-Flow.md#backflow-service).

# Goals

- [x] We need to handle code-flow-enabled subscriptions and exercise this new flow of preparing a PR from a branch that will be asynchronously created by the `.NET Product Construction Service` service.
- [x] We have an E2E scenario tests, similarly to what we have for other flows.
- [x] We handle all the non-happy paths and edge cases when things go wrong.

**Comment by mmitche** [comment]
Costing in https://github.com/dotnet/arcade-services/issues/2994

**Comment by premun** [comment]
This is now completed
