### ISSUE TITLE
CLI Blob Storage Reliability

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#3028]
The main goal is to automatically update the `latest.version` files in the blob storages and ensure that the `dotnet-install.ps1` script gets the right bits.

## Milestones
- [ ] https://github.com/dotnet/release/issues/374
- [x] https://github.com/dotnet/arcade-services/issues/3029
- [ ] Update the subscription between `dotnet/arcade` and `dotnet-release` to auto-merge dependency updates. See https://github.com/dotnet/release/issues/672

## Linked issues:
- https://github.com/dotnet/release/issues/677
Is there anything that can be done on our side to ensure that this problem never occurs again?
The issue occurred because some assets were manually copied, and the incorrect ones were selected.

**Comment by andriipatsula** [comment]
Closing this issue as it is no longer planned.
