### ISSUE TITLE
Switch to the new flat dependency flow between VMR and product repos

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#3170]
## Context

This epic tracks execution of the plan created in https://github.com/dotnet/arcade-services/issues/4505 to move move all product repositories onto the new flat dependency flow.

## Goals

- Subscription configuration is backed up so that it can be restored in case of a rollback.
- Every repository is migrated using tooling created as part of https://github.com/dotnet/arcade-services/issues/4505
- A successful forward and backward flow is performed for every product repository.

## The migration plan goes as follows

The plan is the following:

| Date       | Action                                                                                                      | Owner(s)                            |
|------------|-------------------------------------------------------------------------------------------------------------|----------------------------------|
| April 2nd  | Flat dependency flow migration is announced and introduced to developers in a *.NET Platform Talks* session | premun, mmitche        |
| April 3rd | Migration announced at Tactics with communication sent out to .NET M2s and .NET Partners                    | mmitche                     |
| April 10th | Migration reminded and further details sent out to .NET Partners                                            | mmitche, premun        |
| April 17th | Migration reminded and further details sent out to .NET Partners                                            | mmitche, premun        |
| April 17th | Dependency flow data collected for old flow\*                                            | mmitche, premun        |
| April 24th | Product repositories are migrated to the flat dependency flow                                               | dotnet/product-construction |

_\* On April 17th, we should additionally collect subscription data:_
- _How many PRs opened for Preview 3 and 4, how many opened in main - basically how much flowing do we need per a release_
- _We now have the data (https://github.com/dotnet/arcade-services/pull/4542)_

#### On April 23rd:
- [x] Check if there are no SB patches left in the VMR and try removing them non-forcefully

#### On April 24th, we will:

- [x] Check if there are no SB patches left in the VMR
  - If there are, we will remove them, force merge the removal and re-introduce them later directly in the VMR
- [x] Send out comms
- [x] Turn off the current `dotnet-dotnet-synchronization` pipeline for `main` and `release/10*` branches
  - https://github.com/dotnet/sdk/pull/48479
- [x] Merge the PR that turns on promotion of NuGet.Client builds
  - https://github.com/dotnet/sdk/pull/48311  
- [x] Migrate repositories
